global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
- job_name: node
  scrape_interval: 5s
  static_configs:
   # Replace target with ip of gateway or the target on EKS
   - targets: ['host.docker.internal:8080']